on:
  pull_request:

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: pwd
        run: pwd
      - name: ls -l
        run: ls -l
      - name: ls /
        run: ls -l /
      - name: find /opt
        run: find /opt -type f
      - name: check python3 version
        run: python3 -V
      - name: setup ansible
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install ansible
          ansible --version
