on:
  pull_request:

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: pwd
        run: |
          pwd
      - name: ls
        run: |
          ls -l /
      - name: python3
        run: |
          python3 -V
      - name: setup ansible
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install ansible
      - name: ansible version
        run: |
          ansible --version
